# Generated by Django 4.0.2 on 2022-05-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='list',
            name='podcast',
        ),
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.list')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.episode')),
                ('podcast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.podcast')),
            ],
        ),
    ]
