# Generated by Django 4.0.2 on 2022-05-11 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_list_episode_remove_list_podcast_listcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcontent',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.episode'),
        ),
        migrations.AlterField(
            model_name='listcontent',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.podcast'),
        ),
    ]
