# Generated by Django 4.0.2 on 2022-05-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_listcontent_episode_alter_listcontent_podcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='avgScore',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='avgScore',
        ),
    ]
